spring:
  application:
    name: spring-security

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        highlight_sql: true